# Generated by Django 4.2.3 on 2023-07-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
    ]
