# Generated by Django 4.2.3 on 2023-07-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
